# .github/workflows/pages.yml
name: Deploy GH Pages (frontend)
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload frontend
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend
      - name: Deploy to GH Pages
        uses: actions/deploy-pages@v4
